import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "swiper/css";
import "./globals.css";
import StoreProvider from "./StoreProvider";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="ru">
        <head>
          <link rel="icon.svg" href="/icon" type="image/svg+xml" />
        </head>
        <body className={`${roboto.variable}`}>{children}</body>
      </html>
    </StoreProvider>
  );
}
